// GENERATED by scripts/build-presets.mjs from presets/*.json — DO NOT EDIT.
// Run `npm run build:presets` after editing a preset JSON.

export interface Preset {
  readonly name: string;
  readonly label: string;
  readonly description: string;
  readonly sciencePlotsBase: readonly string[];
  readonly typography: {
    readonly family: string;
    readonly familyMono: string;
    readonly familySerif: string;
    readonly size: {
      readonly base: number;
      readonly title: number;
      readonly label: number;
      readonly tick: number;
      readonly legend: number;
    };
  };
  readonly palette: {
    readonly categorical: readonly string[];
    readonly defaultColor: string;
    readonly sequential: string;
    readonly diverging: string;
  };
  readonly geometry: {
    readonly lineWidth: number;
    readonly markerSize: number;
    readonly barGap: number;
    readonly figSize: readonly [number, number];
    readonly dpi: number;
    readonly margin: { readonly l: number; readonly r: number; readonly t: number; readonly b: number };
  };
  readonly modes: {
    readonly light: PresetMode;
    readonly dark: PresetMode;
  };
}

export interface PresetMode {
  readonly background: string;
  readonly figureFace: string;
  readonly foreground: string;
  readonly gridColor: string;
  readonly gridColorSolid: string;
  readonly tickColor: string;
  readonly highlightRing: string;
}

export const PRESETS = {
  "molplot": {
    "name": "molplot",
    "label": "MolPlot",
    "description": "MolCrafts unified scientific charting preset, faithful to scienceplots' 'science' base — its standard seven-colour cycle, thin 1.0 pt lines, serif type, and black-on-white axes — so a browser chart and a matplotlib figure share the same scienceplots look.",
    "sciencePlotsBase": [
      "science",
      "no-latex"
    ],
    "typography": {
      "family": "Times New Roman, Times, Nimbus Roman, serif",
      "familyMono": "ui-monospace, SFMono-Regular, Menlo, Consolas, monospace",
      "familySerif": "Times New Roman, Times, Nimbus Roman, serif",
      "size": {
        "base": 10,
        "title": 12,
        "label": 10,
        "tick": 9,
        "legend": 9
      }
    },
    "palette": {
      "categorical": [
        "#0c5da5",
        "#00b945",
        "#ff9500",
        "#ff2c00",
        "#845b97",
        "#474747",
        "#9e9e9e"
      ],
      "defaultColor": "#0c5da5",
      "sequential": "viridis",
      "diverging": "RdBu"
    },
    "geometry": {
      "lineWidth": 1,
      "markerSize": 6,
      "barGap": 0.2,
      "figSize": [
        3.5,
        2.625
      ],
      "dpi": 400,
      "margin": {
        "l": 40,
        "r": 10,
        "t": 10,
        "b": 40
      }
    },
    "modes": {
      "light": {
        "background": "transparent",
        "figureFace": "#ffffff",
        "foreground": "#000000",
        "gridColor": "rgba(0,0,0,0.10)",
        "gridColorSolid": "#cccccc",
        "tickColor": "#000000",
        "highlightRing": "#111827"
      },
      "dark": {
        "background": "transparent",
        "figureFace": "#111113",
        "foreground": "#e5e5e5",
        "gridColor": "rgba(255,255,255,0.10)",
        "gridColorSolid": "#444444",
        "tickColor": "#e5e5e5",
        "highlightRing": "#f9fafb"
      }
    }
  } as const,
  "molplot-paper": {
    "name": "molplot-paper",
    "label": "MolPlot Paper",
    "description": "Publication variant layered on scienceplots' 'science' + 'nature' bases — the same standard seven-colour cycle as the default, thin 1.0 pt lines and serif type, but a tighter single-column figure and higher DPI. Web and paper figures stay colour-consistent.",
    "sciencePlotsBase": [
      "science",
      "nature",
      "no-latex"
    ],
    "typography": {
      "family": "Times New Roman, Times, Nimbus Roman, serif",
      "familyMono": "ui-monospace, SFMono-Regular, Menlo, Consolas, monospace",
      "familySerif": "Times New Roman, Times, Nimbus Roman, serif",
      "size": {
        "base": 9,
        "title": 10,
        "label": 9,
        "tick": 8,
        "legend": 8
      }
    },
    "palette": {
      "categorical": [
        "#0c5da5",
        "#00b945",
        "#ff9500",
        "#ff2c00",
        "#845b97",
        "#474747",
        "#9e9e9e"
      ],
      "defaultColor": "#0c5da5",
      "sequential": "viridis",
      "diverging": "RdBu"
    },
    "geometry": {
      "lineWidth": 1,
      "markerSize": 3,
      "barGap": 0.2,
      "figSize": [
        3.3,
        2.5
      ],
      "dpi": 600,
      "margin": {
        "l": 44,
        "r": 8,
        "t": 8,
        "b": 40
      }
    },
    "modes": {
      "light": {
        "background": "transparent",
        "figureFace": "#ffffff",
        "foreground": "#000000",
        "gridColor": "rgba(0,0,0,0.10)",
        "gridColorSolid": "#cccccc",
        "tickColor": "#000000",
        "highlightRing": "#000000"
      },
      "dark": {
        "background": "transparent",
        "figureFace": "#111113",
        "foreground": "#e5e5e5",
        "gridColor": "rgba(255,255,255,0.10)",
        "gridColorSolid": "#444444",
        "tickColor": "#e5e5e5",
        "highlightRing": "#ffffff"
      }
    }
  } as const,
} satisfies Record<string, Preset>;

export type PresetName = "molplot" | "molplot-paper";

export const DEFAULT_PRESET: PresetName = "molplot";
