#!/usr/bin/env node
/**
 * build-presets — the single-source-of-truth compiler for MolPlot presets.
 *
 * Reads every `presets/<name>.json` (the human-editable design tokens) and
 * emits the per-package, self-contained copies each renderer bundles:
 *
 *   core/src/presets/generated.ts          typed const map for the web renderer
 *   python/src/molplot/presets/_generated.py   dict for the matplotlib renderer
 *   python/src/molplot/presets/<name>.mplstyle       light matplotlib style
 *   python/src/molplot/presets/<name>-dark.mplstyle  dark matplotlib style
 *
 * Output is deterministic (stable key order, trailing newline) so CI can run
 * this and assert `git diff --exit-code` — a drift guard that keeps the two
 * renderers pixel-consistent. Never hand-edit the generated files.
 *
 * Usage:  node scripts/build-presets.mjs [--check]
 *   --check  generate into memory and fail if it differs from disk
 */
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const PRESET_DIR = join(ROOT, "presets");
const TS_OUT = join(ROOT, "core", "src", "presets", "generated.ts");
const PY_DIR = join(ROOT, "python", "src", "molplot", "presets");
const PY_OUT = join(PY_DIR, "_generated.py");

const check = process.argv.includes("--check");

/** Load every preset json, sorted by name for stable output. */
function loadPresets() {
  return readdirSync(PRESET_DIR)
    .filter((f) => f.endsWith(".json") && f !== "preset.schema.json")
    .sort()
    .map((f) => JSON.parse(readFileSync(join(PRESET_DIR, f), "utf8")))
    .sort((a, b) => a.name.localeCompare(b.name));
}

/** Strip the leading `#` from a hex colour for matplotlib mplstyle syntax. */
const noHash = (c) => c.replace(/^#/, "");
/** Serif iff the *primary* family reads as a serif face (not "sans-serif"). */
const isSerif = (family) => {
  const primary = family.split(",")[0].trim().toLowerCase();
  if (primary.includes("sans")) return false;
  return /serif|times|roman|georgia|garamond|nimbus/.test(primary);
};

// ── TypeScript ────────────────────────────────────────────────────────────
function renderTs(presets) {
  const banner =
    "// GENERATED by scripts/build-presets.mjs from presets/*.json — DO NOT EDIT.\n" +
    "// Run `npm run build:presets` after editing a preset JSON.\n\n";
  const type = `export interface Preset {
  readonly name: string;
  readonly label: string;
  readonly description: string;
  readonly sciencePlotsBase: readonly string[];
  readonly typography: {
    readonly family: string;
    readonly familyMono: string;
    readonly familySerif: string;
    readonly size: {
      readonly base: number;
      readonly title: number;
      readonly label: number;
      readonly tick: number;
      readonly legend: number;
    };
  };
  readonly palette: {
    readonly categorical: readonly string[];
    readonly defaultColor: string;
    readonly sequential: string;
    readonly diverging: string;
  };
  readonly geometry: {
    readonly lineWidth: number;
    readonly markerSize: number;
    readonly barGap: number;
    readonly figSize: readonly [number, number];
    readonly dpi: number;
    readonly margin: { readonly l: number; readonly r: number; readonly t: number; readonly b: number };
  };
  readonly modes: {
    readonly light: PresetMode;
    readonly dark: PresetMode;
  };
}

export interface PresetMode {
  readonly background: string;
  readonly figureFace: string;
  readonly foreground: string;
  readonly gridColor: string;
  readonly gridColorSolid: string;
  readonly tickColor: string;
  readonly highlightRing: string;
}

`;
  const body = presets
    .map((p) => {
      const { $schema, ...rest } = p;
      return `  ${JSON.stringify(p.name)}: ${JSON.stringify(rest, null, 2).replace(/\n/g, "\n  ")} as const,`;
    })
    .join("\n");
  const names = presets.map((p) => JSON.stringify(p.name)).join(" | ");
  const map = `export const PRESETS = {\n${body}\n} satisfies Record<string, Preset>;\n\n`;
  const helpers =
    `export type PresetName = ${names};\n\n` +
    `export const DEFAULT_PRESET: PresetName = "molplot";\n`;
  return banner + type + map + helpers;
}

// ── Python ────────────────────────────────────────────────────────────────
function renderPy(presets) {
  const banner =
    '"""GENERATED by scripts/build-presets.mjs from presets/*.json — DO NOT EDIT.\n\n' +
    "Run ``npm run build:presets`` after editing a preset JSON.\n" +
    '"""\n\nfrom __future__ import annotations\n\n';
  // JSON is valid Python for our token subset once True/False are irrelevant
  // (no booleans present) — emit as a dict literal for zero-dependency import.
  const entries = presets
    .map((p) => `    ${pyStr(p.name)}: ${pyValue(p, 1)},`)
    .join("\n");
  const map = `PRESETS: dict = {\n${entries}\n}\n\n`;
  const helpers = `DEFAULT_PRESET = "molplot"\n\nPRESET_NAMES = ${pyValue(
    presets.map((p) => p.name),
    0,
  )}\n`;
  return banner + map + helpers;
}

function pyStr(s) {
  return JSON.stringify(s);
}
function pyValue(v, depth) {
  const pad = "    ".repeat(depth + 1);
  const padEnd = "    ".repeat(depth);
  if (Array.isArray(v)) {
    if (v.length === 0) return "[]";
    const items = v.map((x) => `${pad}${pyValue(x, depth + 1)},`).join("\n");
    return `[\n${items}\n${padEnd}]`;
  }
  if (v && typeof v === "object") {
    const keys = Object.keys(v).filter((k) => k !== "$schema");
    const items = keys
      .map((k) => `${pad}${pyStr(k)}: ${pyValue(v[k], depth + 1)},`)
      .join("\n");
    return `{\n${items}\n${padEnd}}`;
  }
  if (typeof v === "string") return pyStr(v);
  return String(v);
}

// ── matplotlib .mplstyle ──────────────────────────────────────────────────
function renderMplstyle(preset, modeName) {
  const m = preset.modes[modeName];
  const t = preset.typography;
  const g = preset.geometry;
  const serif = isSerif(t.family);
  const cycle = preset.palette.categorical
    .map((c) => `'${noHash(c)}'`)
    .join(", ");
  const lines = [
    `# GENERATED by scripts/build-presets.mjs from presets/${preset.name}.json — DO NOT EDIT.`,
    `# MolPlot preset "${preset.name}" (${modeName}). Layer under scienceplots: ${preset.sciencePlotsBase.join(", ")}`,
    "",
    `figure.figsize: ${g.figSize[0]}, ${g.figSize[1]}`,
    `figure.dpi: ${g.dpi}`,
    `savefig.dpi: ${g.dpi}`,
    `savefig.bbox: tight`,
    `figure.facecolor: ${noHash(m.figureFace)}`,
    `axes.facecolor: ${noHash(m.figureFace)}`,
    `savefig.facecolor: ${noHash(m.figureFace)}`,
    "",
    `font.family: ${serif ? "serif" : "sans-serif"}`,
    serif ? `font.serif: ${t.family}` : `font.sans-serif: ${t.family}`,
    `font.size: ${t.size.base}`,
    `axes.titlesize: ${t.size.title}`,
    `axes.labelsize: ${t.size.label}`,
    `xtick.labelsize: ${t.size.tick}`,
    `ytick.labelsize: ${t.size.tick}`,
    `legend.fontsize: ${t.size.legend}`,
    "",
    `axes.prop_cycle: cycler('color', [${cycle}])`,
    `lines.linewidth: ${g.lineWidth}`,
    `lines.markersize: ${g.markerSize}`,
    "",
    `text.color: ${noHash(m.foreground)}`,
    `axes.edgecolor: ${noHash(m.foreground)}`,
    `axes.labelcolor: ${noHash(m.foreground)}`,
    `xtick.color: ${noHash(m.foreground)}`,
    `ytick.color: ${noHash(m.foreground)}`,
    "",
    `axes.grid: True`,
    `grid.color: ${noHash(m.gridColorSolid)}`,
    `grid.linewidth: 0.5`,
    `grid.alpha: 1.0`,
    `axes.axisbelow: True`,
    "",
    `legend.frameon: False`,
    `legend.fancybox: False`,
  ];
  return `${lines.join("\n")}\n`;
}

// ── drive ─────────────────────────────────────────────────────────────────
const presets = loadPresets();
if (presets.length === 0) {
  console.error("build-presets: no presets found in", PRESET_DIR);
  process.exit(1);
}

const outputs = [
  [TS_OUT, renderTs(presets)],
  [PY_OUT, renderPy(presets)],
];
for (const p of presets) {
  outputs.push([
    join(PY_DIR, `${p.name}.mplstyle`),
    renderMplstyle(p, "light"),
  ]);
  outputs.push([
    join(PY_DIR, `${p.name}-dark.mplstyle`),
    renderMplstyle(p, "dark"),
  ]);
}

let drift = false;
for (const [path, content] of outputs) {
  let current = null;
  try {
    current = readFileSync(path, "utf8");
  } catch {
    /* missing file counts as drift */
  }
  if (current === content) continue;
  drift = true;
  if (check) {
    console.error(`build-presets: OUT OF DATE → ${path}`);
  } else {
    writeFileSync(path, content);
    console.log(`build-presets: wrote ${path}`);
  }
}

if (check && drift) {
  console.error(
    "\nGenerated presets are stale. Run `npm run build:presets` and commit the result.",
  );
  process.exit(1);
}
if (!drift) console.log("build-presets: all outputs up to date");
