"""GENERATED by scripts/build-presets.mjs from presets/*.json — DO NOT EDIT.

Run ``npm run build:presets`` after editing a preset JSON.
"""

from __future__ import annotations

PRESETS: dict = {
    "molplot": {
        "name": "molplot",
        "label": "MolPlot",
        "description": "MolCrafts unified scientific charting preset — the single source of truth shared by the Observable Plot + D3 web renderer and the scienceplots/matplotlib Python renderer.",
        "sciencePlotsBase": [
            "science",
            "no-latex",
        ],
        "typography": {
            "family": "Inter, system-ui, -apple-system, Segoe UI, Roboto, Helvetica, Arial, sans-serif",
            "familyMono": "ui-monospace, SFMono-Regular, Menlo, Consolas, monospace",
            "familySerif": "Times New Roman, Times, Nimbus Roman, serif",
            "size": {
                "base": 10,
                "title": 12,
                "label": 10,
                "tick": 9,
                "legend": 9,
            },
        },
        "palette": {
            "categorical": [
                "#1f77b4",
                "#ff7f0e",
                "#2ca02c",
                "#d62728",
                "#9467bd",
                "#8c564b",
                "#e377c2",
                "#7f7f7f",
                "#bcbd22",
                "#17becf",
                "#aec7e8",
                "#ffbb78",
                "#98df8a",
                "#ff9896",
                "#c5b0d5",
                "#c49c94",
                "#f7b6d2",
                "#c7c7c7",
                "#dbdb8d",
                "#9edae5",
            ],
            "defaultColor": "#60a5fa",
            "sequential": "viridis",
            "diverging": "RdBu",
        },
        "geometry": {
            "lineWidth": 2,
            "markerSize": 6,
            "barGap": 0.2,
            "figSize": [
                3.5,
                2.625,
            ],
            "dpi": 400,
            "margin": {
                "l": 40,
                "r": 10,
                "t": 10,
                "b": 40,
            },
        },
        "modes": {
            "light": {
                "background": "transparent",
                "figureFace": "#ffffff",
                "foreground": "#52525b",
                "gridColor": "rgba(120,120,120,0.18)",
                "gridColorSolid": "#d4d4d8",
                "tickColor": "#a1a1aa",
                "highlightRing": "#111827",
            },
            "dark": {
                "background": "transparent",
                "figureFace": "#111113",
                "foreground": "#d4d4d8",
                "gridColor": "rgba(220,220,220,0.12)",
                "gridColorSolid": "#3f3f46",
                "tickColor": "#71717a",
                "highlightRing": "#f9fafb",
            },
        },
    },
    "molplot-paper": {
        "name": "molplot-paper",
        "label": "MolPlot Paper",
        "description": "Publication variant of the MolPlot preset — serif type, tighter figure, high DPI, layered on scienceplots' 'nature' base. Same categorical palette as the default so web and paper figures stay colour-consistent.",
        "sciencePlotsBase": [
            "science",
            "nature",
            "no-latex",
        ],
        "typography": {
            "family": "Times New Roman, Times, Nimbus Roman, serif",
            "familyMono": "ui-monospace, SFMono-Regular, Menlo, Consolas, monospace",
            "familySerif": "Times New Roman, Times, Nimbus Roman, serif",
            "size": {
                "base": 9,
                "title": 10,
                "label": 9,
                "tick": 8,
                "legend": 8,
            },
        },
        "palette": {
            "categorical": [
                "#1f77b4",
                "#ff7f0e",
                "#2ca02c",
                "#d62728",
                "#9467bd",
                "#8c564b",
                "#e377c2",
                "#7f7f7f",
                "#bcbd22",
                "#17becf",
                "#aec7e8",
                "#ffbb78",
                "#98df8a",
                "#ff9896",
                "#c5b0d5",
                "#c49c94",
                "#f7b6d2",
                "#c7c7c7",
                "#dbdb8d",
                "#9edae5",
            ],
            "defaultColor": "#1f77b4",
            "sequential": "viridis",
            "diverging": "RdBu",
        },
        "geometry": {
            "lineWidth": 1,
            "markerSize": 4,
            "barGap": 0.2,
            "figSize": [
                3.3,
                2.5,
            ],
            "dpi": 600,
            "margin": {
                "l": 44,
                "r": 8,
                "t": 8,
                "b": 40,
            },
        },
        "modes": {
            "light": {
                "background": "transparent",
                "figureFace": "#ffffff",
                "foreground": "#000000",
                "gridColor": "rgba(0,0,0,0.10)",
                "gridColorSolid": "#cccccc",
                "tickColor": "#000000",
                "highlightRing": "#000000",
            },
            "dark": {
                "background": "transparent",
                "figureFace": "#111113",
                "foreground": "#e5e5e5",
                "gridColor": "rgba(255,255,255,0.10)",
                "gridColorSolid": "#444444",
                "tickColor": "#e5e5e5",
                "highlightRing": "#ffffff",
            },
        },
    },
}

DEFAULT_PRESET = "molplot"

PRESET_NAMES = [
    "molplot",
    "molplot-paper",
]
